version: "3.9"

networks:
  relays:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1

volumes:
  postgres:
    driver: local

services:

  base:
    image: network_next_base
    build: 
      context: .
      dockerfile: docker/base.Dockerfile

  postgres:
    build: 
      context: .
      dockerfile: docker/postgres.Dockerfile
    environment:
      POSTGRES_USER: Postgres
      POSTGRES_PASSWORD: Postgres
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - '5436:5432'
    restart: always

  redis:
    image: redis/redis-stack-server:latest
    restart: always

  magic_backend:
    build: 
      context: .
      dockerfile: docker/magic_backend.Dockerfile
    depends_on:
      - base
    ports:
      - "10000:80"

  relay_gateway:
    build: 
      context: .
      dockerfile: docker/relay_gateway.Dockerfile
    ports:
      - "11000:80"
    depends_on:
      - base
      - redis
      - magic_backend
    environment:
      - REDIS_HOSTNAME=redis:6379
      - MAGIC_URL=http://magic_backend/magic
      - MAGIC_INTERVAL=10s
      - RELAY_BACKEND_PUBLIC_KEY=vvAdjFQOyywWcWIJlNe0T1cPyBXa4SVajpQTPYSWNhg=
      - RELAY_BACKEND_PRIVATE_KEY=ddl/8ski0NCedCRyq/CWiElApMXecJCVYzy9CvZjqMg=
      - PING_KEY=qizi4jbiHkg/v3xPnDPtJBhTi3/92OacXJ/nknyHAUQ=
    networks:
      - default
      - relays
    restart: always

  relay_backend:
    build: 
      context: .
      dockerfile: docker/relay_backend.Dockerfile
    ports:
      - "12000:80"
    depends_on:
      - base
      - redis
      - relay_gateway
    environment:
      - REDIS_HOSTNAME=redis:6379
      - ROUTE_MATRIX_INTERVAL=10s
    restart: always

  session_cruncher:
    build: 
      context: .
      dockerfile: docker/session_cruncher.Dockerfile
    depends_on:
      - base
    ports:
      - "40200:80"
    environment:
      - ENABLE_REDIS_TIME_SERIES=true
      - REDIS_TIME_SERIES_HOSTNAME=redis:6379
    restart: always

  server_cruncher:
    build: 
      context: .
      dockerfile: docker/server_cruncher.Dockerfile
    depends_on:
      - base
    ports:
      - "40300:80"
    restart: always

  server_backend:
    build: 
      context: .
      dockerfile: docker/server_backend.Dockerfile
    ports:
      - "13000:80/tcp"
      - "40000:40000/udp"
    depends_on:
      - base
      - magic_backend
      - relay_gateway
    environment:
      - DEBUG_LOGS=1
      - REDIS_HOSTNAME=redis:6379
      - MAGIC_URL=http://magic_backend/magic
      - MAGIC_INTERVAL=10s
      - ROUTE_MATRIX_INTERVAL=10s
      - ROUTE_MATRIX_URL=http://relay_backend/route_matrix
      - SERVER_BACKEND_PUBLIC_KEY=jiAJGx7iWApPM4IQbkFw4u92BsttFH95OZQHUqQMLlc=
      - SERVER_BACKEND_PRIVATE_KEY=UHMg1KA/9g+jwriAGf7rbN5nGbL2sMtaW8rktJudyK6OIAkbHuJYCk8zghBuQXDi73YGy20Uf3k5lAdSpAwuVw==
      - RELAY_BACKEND_PRIVATE_KEY=ddl/8ski0NCedCRyq/CWiElApMXecJCVYzy9CvZjqMg=
      - PING_KEY=qizi4jbiHkg/v3xPnDPtJBhTi3/92OacXJ/nknyHAUQ=
      - SERVER_BACKEND_ADDRESS=10.5.0.100:40000
      - SESSION_CRUNCHER_URL=http://session_cruncher
      - SERVER_CRUNCHER_URL=http://server_cruncher
    networks:
      default:
      relays:
        ipv4_address: 10.5.0.100
    restart: always

  api:
    build: 
      context: .
      dockerfile: docker/api.Dockerfile
    ports:
      - "50000:80"
    depends_on:
      - base
      - redis
      - postgres
      - server_cruncher
      - session_cruncher
    environment:
      - REDIS_HOSTNAME=redis:6379
      - PGSQL_CONFIG=host=postgres port=5432 user=Postgres password=Postgres dbname=postgres sslmode=disable
      - SESSION_CRUNCHER_URL=http://session_cruncher
      - SERVER_CRUNCHER_URL=http://server_cruncher
      - API_PRIVATE_KEY=VywxIjzyZDHnvbLwkmXSexjcVYuUmvBZJBJeqvRHCzDLsGPRHItbENozdIokQzIt
    restart: always

  relay_1:
    build: 
      context: .
      dockerfile: docker/relay.Dockerfile
    environment:
      - RELAY_NAME=relay_1
      - RELAY_PUBLIC_ADDRESS=10.5.0.5:40000
      - RELAY_BACKEND_URL=http://relay_gateway
      - RELAY_PUBLIC_KEY=swNl9YuThlOMQ4jDcbxQYt2uvmv08OZqrgMRzrXtriA=
      - RELAY_PRIVATE_KEY=2h7RT4KEtPSA9z+L5iSOvAWOtb9LBDSThYO0pHzzQC8=
      - RELAY_BACKEND_PUBLIC_KEY=vvAdjFQOyywWcWIJlNe0T1cPyBXa4SVajpQTPYSWNhg=
    networks:
      relays:
        ipv4_address: 10.5.0.5
    depends_on:
      - base
      - relay_backend
    restart: always
    
  relay_2:
    build: 
      context: .
      dockerfile: docker/relay.Dockerfile
    environment:
      - RELAY_NAME=relay_2
      - RELAY_PUBLIC_ADDRESS=10.5.0.6:40000
      - RELAY_BACKEND_URL=http://relay_gateway
      - RELAY_PUBLIC_KEY=swNl9YuThlOMQ4jDcbxQYt2uvmv08OZqrgMRzrXtriA=
      - RELAY_PRIVATE_KEY=2h7RT4KEtPSA9z+L5iSOvAWOtb9LBDSThYO0pHzzQC8=
      - RELAY_BACKEND_PUBLIC_KEY=vvAdjFQOyywWcWIJlNe0T1cPyBXa4SVajpQTPYSWNhg=
    networks:
      relays:
        ipv4_address: 10.5.0.6
    depends_on:
      - base
      - relay_backend
    restart: always

  relay_3:
    build: 
      context: .
      dockerfile: docker/relay.Dockerfile
    environment:
      - RELAY_NAME=relay_3
      - RELAY_PUBLIC_ADDRESS=10.5.0.7:40000
      - RELAY_BACKEND_URL=http://relay_gateway
      - RELAY_PUBLIC_KEY=swNl9YuThlOMQ4jDcbxQYt2uvmv08OZqrgMRzrXtriA=
      - RELAY_PRIVATE_KEY=2h7RT4KEtPSA9z+L5iSOvAWOtb9LBDSThYO0pHzzQC8=
      - RELAY_BACKEND_PUBLIC_KEY=vvAdjFQOyywWcWIJlNe0T1cPyBXa4SVajpQTPYSWNhg=
    networks:
      relays:
        ipv4_address: 10.5.0.7
    depends_on:
      - base
      - relay_backend
    restart: always

  relay_4:
    build: 
      context: .
      dockerfile: docker/relay.Dockerfile
    environment:
      - RELAY_NAME=relay_4
      - RELAY_PUBLIC_ADDRESS=10.5.0.8:40000
      - RELAY_BACKEND_URL=http://relay_gateway
      - RELAY_PUBLIC_KEY=swNl9YuThlOMQ4jDcbxQYt2uvmv08OZqrgMRzrXtriA=
      - RELAY_PRIVATE_KEY=2h7RT4KEtPSA9z+L5iSOvAWOtb9LBDSThYO0pHzzQC8=
      - RELAY_BACKEND_PUBLIC_KEY=vvAdjFQOyywWcWIJlNe0T1cPyBXa4SVajpQTPYSWNhg=
    networks:
      relays:
        ipv4_address: 10.5.0.8
    depends_on:
      - base
      - relay_backend
    restart: always

  relay_5:
    build: 
      context: .
      dockerfile: docker/relay.Dockerfile
    environment:
      - RELAY_NAME=relay_5
      - RELAY_PUBLIC_ADDRESS=10.5.0.9:40000
      - RELAY_BACKEND_URL=http://relay_gateway
      - RELAY_PUBLIC_KEY=swNl9YuThlOMQ4jDcbxQYt2uvmv08OZqrgMRzrXtriA=
      - RELAY_PRIVATE_KEY=2h7RT4KEtPSA9z+L5iSOvAWOtb9LBDSThYO0pHzzQC8=
      - RELAY_BACKEND_PUBLIC_KEY=vvAdjFQOyywWcWIJlNe0T1cPyBXa4SVajpQTPYSWNhg=
    networks:
      relays:
        ipv4_address: 10.5.0.9
    depends_on:
      - base
      - relay_backend
    restart: always

  server:
    build: 
      context: .
      dockerfile: docker/server.Dockerfile
    environment:
      - NEXT_LOG_LEVEL=4
      - NEXT_DELAY=1
      - NEXT_DATACENTER=local
      - NEXT_SERVER_ADDRESS=10.5.0.20
      - NEXT_SERVER_BACKEND_HOSTNAME=server_backend
      - NEXT_BUYER_PUBLIC_KEY=AN+VWuqgAQfd5d+QeT6apNf+Gbb9rqFBMtk5M+GoMvwS1Eqz764X/A==
      - NEXT_BUYER_PRIVATE_KEY=AN+VWuqgAQdhmzB4XOT89baswrIaX6WS7dTIW8U6deMZdoemQh9qoN3l35B5Ppqk1/4Ztv2uoUEy2Tkz4agy/BLUSrPvrhf8
      - NEXT_SERVER_BACKEND_PUBLIC_KEY=jiAJGx7iWApPM4IQbkFw4u92BsttFH95OZQHUqQMLlc=
      - NEXT_RELAY_BACKEND_PUBLIC_KEY=vvAdjFQOyywWcWIJlNe0T1cPyBXa4SVajpQTPYSWNhg=
    networks:
      relays:
        ipv4_address: 10.5.0.20
    depends_on:
      - base
      - server_backend
    restart: always

  client:
    build: 
      context: .
      dockerfile: docker/client.Dockerfile
    environment:
      - NEXT_DELAY=1
      - NEXT_CONNECT_ADDRESS=10.5.0.20:30000
      - NEXT_BUYER_PUBLIC_KEY=AN+VWuqgAQfd5d+QeT6apNf+Gbb9rqFBMtk5M+GoMvwS1Eqz764X/A==
      - NEXT_SERVER_BACKEND_PUBLIC_KEY=jiAJGx7iWApPM4IQbkFw4u92BsttFH95OZQHUqQMLlc=
      - NEXT_RELAY_BACKEND_PUBLIC_KEY=vvAdjFQOyywWcWIJlNe0T1cPyBXa4SVajpQTPYSWNhg=
    networks:
      relays:
        ipv4_address: 10.5.0.30
    depends_on:
      - base
      - server_backend
    restart: always

  portal:
    build:
      context: .
      dockerfile: docker/portal.Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - api
    restart: always

  raspberry_backend:
    build: 
      context: .
      dockerfile: docker/raspberry_backend.Dockerfile
    depends_on:
      - base
    ports:
      - "40100:80"
    environment:
      - REDIS_HOSTNAME=redis:6379
