version: "3.9"

services:

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: developer
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:6.2-alpine
    restart: always

  magic_backend:
    build: 
      context: .
      dockerfile: docker/magic_backend.Dockerfile
    ports:
      - "10000:80"

  relay_gateway:
    build: 
      context: .
      dockerfile: docker/relay_gateway.Dockerfile
    ports:
      - "11000:80"
    depends_on:
      - redis
      - magic_backend
    environment:
      - REDIS_HOSTNAME=redis:6379
      - MAGIC_URL=http://magic_backend/magic
      - MAGIC_INTERVAL=10s
      - RELAY_BACKEND_PUBLIC_KEY=SS55dEl9nTSnVVDrqwPeqRv/YcYOZZLXCWTpNBIyX0Y=
      - RELAY_BACKEND_PRIVATE_KEY=ls5XiwAZRCfyuZAbQ1b9T1bh2VZY8vQ7hp8SdSTSR7M=

  relay_backend:
    build: 
      context: .
      dockerfile: docker/relay_backend.Dockerfile
    ports:
      - "12000:80"
    depends_on:
      - redis
      - relay_gateway
    environment:
      - REDIS_HOSTNAME=redis:6379
      - ROUTE_MATRIX_INTERVAL=10s

  server_backend:
    build: 
      context: .
      dockerfile: docker/server_backend.Dockerfile
    ports:
      - "13000:80/tcp"
      - "45000:40000/udp"
    depends_on:
      - magic_backend
      - relay_gateway
    environment:
      - REDIS_HOSTNAME=redis:6379
      - MAGIC_URL=http://magic_backend/magic
      - MAGIC_INTERVAL=10s
      - ROUTE_MATRIX_INTERVAL=10s
      - ROUTE_MATRIX_URL=http://relay_backend/route_matrix
      - SERVER_BACKEND_PUBLIC_KEY=TGHKjEeHPtSgtZfDyuDPcQgtJTyRDtRvGSKvuiWWo0A=
      - SERVER_BACKEND_PRIVATE_KEY=FXwFqzjGlIwUDwiq1N5Um5VUesdr4fP2hVV2cnJ+yARMYcqMR4c+1KC1l8PK4M9xCC0lPJEO1G8ZIq+6JZajQA==
      - RELAY_BACKEND_PRIVATE_KEY=ls5XiwAZRCfyuZAbQ1b9T1bh2VZY8vQ7hp8SdSTSR7M=

  portal_cruncher:
    build: 
      context: .
      dockerfile: docker/portal_cruncher.Dockerfile
    ports:
      - "14000:80"
    depends_on:
      - redis
    environment:
      - REDIS_HOSTNAME=redis:6379

  map_cruncher:
    build: 
      context: .
      dockerfile: docker/map_cruncher.Dockerfile
    ports:
      - "15000:80"
    depends_on:
      - redis
    environment:
      - REDIS_HOSTNAME=redis:6379

  analytics:
    build: 
      context: .
      dockerfile: docker/analytics.Dockerfile
    ports:
      - "16000:80"
    depends_on:
      - redis
      - relay_backend
    environment:
      - REDIS_HOSTNAME=redis:6379
      - COST_MATRIX_URL=http://relay_backend/cost_matrix
      - ROUTE_MATRIX_URL=http://relay_backend/route_matrix

  api:
    build: 
      context: .
      dockerfile: docker/api.Dockerfile
    ports:
      - "50000:80"
    depends_on:
      - redis
      - postgres
    environment:
      - REDIS_HOSTNAME=redis:6379
      - PGSQL_CONFIG=host=postgres port=5432 user=developer password=developer dbname=postgres sslmode=disable
      - API_PRIVATE_KEY=this is the private key that generates API keys. make sure you change this value in production
    
volumes:
  postgres:
    driver: local
