version: "3.9"

services:

  base:
    image: network_next_base
    build: 
      context: .
      dockerfile: docker/base.Dockerfile

  postgres:
    build: 
      context: .
      dockerfile: docker/postgres.Dockerfile
    environment:
      POSTGRES_USER: Postgres
      POSTGRES_PASSWORD: Postgres
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - '5436:5432'
    restart: always

  redis:
    image: redis:6.2-alpine
    restart: always

  magic_backend:
    build: 
      context: .
      dockerfile: docker/magic_backend.Dockerfile
    depends_on:
      - base
    ports:
      - "10000:80"

  relay_gateway:
    build: 
      context: .
      dockerfile: docker/relay_gateway.Dockerfile
    ports:
      - "11000:80"
    depends_on:
      - base
      - redis
      - magic_backend
    environment:
      - REDIS_HOSTNAME=redis:6379
      - MAGIC_URL=http://magic_backend/magic
      - MAGIC_INTERVAL=10s
      - RELAY_BACKEND_PUBLIC_KEY=aKfSxzeJIvqTR76M+d2MVcsBDgXYaTVonLvC98X2hGs=
      - RELAY_BACKEND_PRIVATE_KEY=6TDOrOv+8quOoxyEnU7Za2jqx4ExnO6hYN+KA6KF1+Q=
      - PING_KEY=piBNpEvB+iPtny6v+dR/qewuror3AjAmrJLjh7tlINw=
    networks:
      - default
      - relays

  relay_backend:
    build: 
      context: .
      dockerfile: docker/relay_backend.Dockerfile
    ports:
      - "12000:80"
    depends_on:
      - base
      - redis
      - relay_gateway
    environment:
      - REDIS_HOSTNAME=redis:6379
      - ROUTE_MATRIX_INTERVAL=10s

  server_backend:
    build: 
      context: .
      dockerfile: docker/server_backend.Dockerfile
    ports:
      - "13000:80/tcp"
      - "45000:40000/udp"
    depends_on:
      - base
      - magic_backend
      - relay_gateway
    environment:
      - REDIS_HOSTNAME=redis:6379
      - MAGIC_URL=http://magic_backend/magic
      - MAGIC_INTERVAL=10s
      - ROUTE_MATRIX_INTERVAL=10s
      - ROUTE_MATRIX_URL=http://relay_backend/route_matrix
      - SERVER_BACKEND_PUBLIC_KEY=kvgXlg9Xi+dfVutuq2yCReh6exlsy6J8l3IJ6XeargQ=
      - SERVER_BACKEND_PRIVATE_KEY=C8M1NsfSd94k++eW1g6h12POFw33nKrlARtUdDT7Q7SS+BeWD1eL519W626rbIJF6Hp7GWzLonyXcgnpd5quBA==
      - RELAY_BACKEND_PRIVATE_KEY=6TDOrOv+8quOoxyEnU7Za2jqx4ExnO6hYN+KA6KF1+Q=
      - SERVER_BACKEND_ADDRESS=10.5.0.100:40000
      - PING_KEY=piBNpEvB+iPtny6v+dR/qewuror3AjAmrJLjh7tlINw=
    networks:
      default:
      relays:
        ipv4_address: 10.5.0.100

  api:
    build: 
      context: .
      dockerfile: docker/api.Dockerfile
    ports:
      - "50000:80"
    depends_on:
      - base
      - redis
      - postgres
    environment:
      - REDIS_HOSTNAME=redis:6379
      - PGSQL_CONFIG=host=postgres port=5432 user=Postgres password=Postgres dbname=postgres sslmode=disable
      - API_PRIVATE_KEY=this is the private key that generates API keys. make sure you change this value in production
    restart: always

  relay_1:
    build: 
      context: .
      dockerfile: docker/relay.Dockerfile
    environment:
      - RELAY_NAME=relay_1
      - RELAY_PUBLIC_ADDRESS=10.5.0.5:40000
      - RELAY_PUBLIC_KEY=8ixmdMQmh8kSlucuC19Ept7Vtmvat+rexnXB0ntjSR0=
      - RELAY_PRIVATE_KEY=x+5L9CLvHz/NBg/Rmh/EbcI9X4LsLDMzN72ExNpgPC8=
      - RELAY_BACKEND_URL=http://relay_gateway
      - RELAY_BACKEND_PUBLIC_KEY=aKfSxzeJIvqTR76M+d2MVcsBDgXYaTVonLvC98X2hGs=
    networks:
      relays:
        ipv4_address: 10.5.0.5
    depends_on:
      - base
      - relay_backend
    
  relay_2:
    build: 
      context: .
      dockerfile: docker/relay.Dockerfile
    environment:
      - RELAY_NAME=relay_2
      - RELAY_PUBLIC_ADDRESS=10.5.0.6:40000
      - RELAY_PUBLIC_KEY=8ixmdMQmh8kSlucuC19Ept7Vtmvat+rexnXB0ntjSR0=
      - RELAY_PRIVATE_KEY=x+5L9CLvHz/NBg/Rmh/EbcI9X4LsLDMzN72ExNpgPC8=
      - RELAY_BACKEND_URL=http://relay_gateway
      - RELAY_BACKEND_PUBLIC_KEY=aKfSxzeJIvqTR76M+d2MVcsBDgXYaTVonLvC98X2hGs=
    networks:
      relays:
        ipv4_address: 10.5.0.6
    depends_on:
      - base
      - relay_backend

  relay_3:
    build: 
      context: .
      dockerfile: docker/relay.Dockerfile
    environment:
      - RELAY_NAME=relay_3
      - RELAY_PUBLIC_ADDRESS=10.5.0.7:40000
      - RELAY_PUBLIC_KEY=8ixmdMQmh8kSlucuC19Ept7Vtmvat+rexnXB0ntjSR0=
      - RELAY_PRIVATE_KEY=x+5L9CLvHz/NBg/Rmh/EbcI9X4LsLDMzN72ExNpgPC8=
      - RELAY_BACKEND_URL=http://relay_gateway
      - RELAY_BACKEND_PUBLIC_KEY=aKfSxzeJIvqTR76M+d2MVcsBDgXYaTVonLvC98X2hGs=
    networks:
      relays:
        ipv4_address: 10.5.0.7
    depends_on:
      - base
      - relay_backend

  relay_4:
    build: 
      context: .
      dockerfile: docker/relay.Dockerfile
    environment:
      - RELAY_NAME=relay_4
      - RELAY_PUBLIC_ADDRESS=10.5.0.8:40000
      - RELAY_PUBLIC_KEY=8ixmdMQmh8kSlucuC19Ept7Vtmvat+rexnXB0ntjSR0=
      - RELAY_PRIVATE_KEY=x+5L9CLvHz/NBg/Rmh/EbcI9X4LsLDMzN72ExNpgPC8=
      - RELAY_BACKEND_URL=http://relay_gateway
      - RELAY_BACKEND_PUBLIC_KEY=aKfSxzeJIvqTR76M+d2MVcsBDgXYaTVonLvC98X2hGs=
    networks:
      relays:
        ipv4_address: 10.5.0.8
    depends_on:
      - base
      - relay_backend

  relay_5:
    build: 
      context: .
      dockerfile: docker/relay.Dockerfile
    environment:
      - RELAY_NAME=relay_5
      - RELAY_PUBLIC_ADDRESS=10.5.0.9:40000
      - RELAY_PUBLIC_KEY=8ixmdMQmh8kSlucuC19Ept7Vtmvat+rexnXB0ntjSR0=
      - RELAY_PRIVATE_KEY=x+5L9CLvHz/NBg/Rmh/EbcI9X4LsLDMzN72ExNpgPC8=
      - RELAY_BACKEND_URL=http://relay_gateway
      - RELAY_BACKEND_PUBLIC_KEY=aKfSxzeJIvqTR76M+d2MVcsBDgXYaTVonLvC98X2hGs=
    networks:
      relays:
        ipv4_address: 10.5.0.9
    depends_on:
      - base
      - relay_backend

  server:
    build: 
      context: .
      dockerfile: docker/server.Dockerfile
    environment:
      - NEXT_DELAY=1
      - NEXT_DATACENTER=local
      - NEXT_SERVER_ADDRESS=10.5.0.20
      - NEXT_BUYER_PUBLIC_KEY=WC6mKDnJmlHPsrvfii0WFJXExS3cVRJK+Hv1wWX1gRuISdNtuklkYw==
      - NEXT_BUYER_PRIVATE_KEY=WC6mKDnJmlGOqyEK8CCxCE58KXEyeCCJMSJOP9K/Bh34tUl5WbwZ1s+yu9+KLRYUlcTFLdxVEkr4e/XBZfWBG4hJ0226SWRj
      - NEXT_SERVER_BACKEND_HOSTNAME=server_backend
    networks:
      relays:
        ipv4_address: 10.5.0.20
    depends_on:
      - base
      - server_backend

  client:
    build: 
      context: .
      dockerfile: docker/client.Dockerfile
    environment:
      - NEXT_DELAY=1
      - NEXT_CONNECT_ADDRESS=10.5.0.20:30000
      - NEXT_BUYER_PUBLIC_KEY=WC6mKDnJmlHPsrvfii0WFJXExS3cVRJK+Hv1wWX1gRuISdNtuklkYw==
    networks:
      relays:
        ipv4_address: 10.5.0.30
    depends_on:
      - base
      - server_backend

  portal:
    build:
      context: .
      dockerfile: docker/portal.Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - api

networks:
  relays:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1

volumes:
  postgres:
    driver: local
