version: "3.9"

services:

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: developer
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    healthcheck:
      test: pg_isready -U developer -d postgres
      interval: 5s
      timeout: 3s
      retries: 3

  redis:
    image: redis:6.2-alpine
    restart: always

  magic_backend:
    build: 
      context: .
      dockerfile: docker/magic_backend.Dockerfile
    ports:
      - "10000:80"

  relay_gateway:
    build: 
      context: .
      dockerfile: docker/relay_gateway.Dockerfile
    ports:
      - "11000:80"
    depends_on:
      - redis
      - magic_backend
    environment:
      - REDIS_HOSTNAME=redis:6379
      - MAGIC_URL=http://magic_backend/magic
      - MAGIC_INTERVAL=10s
      - RELAY_BACKEND_PUBLIC_KEY=SS55dEl9nTSnVVDrqwPeqRv/YcYOZZLXCWTpNBIyX0Y=
      - RELAY_BACKEND_PRIVATE_KEY=ls5XiwAZRCfyuZAbQ1b9T1bh2VZY8vQ7hp8SdSTSR7M=
    networks:
      - default
      - relays

  relay_backend:
    build: 
      context: .
      dockerfile: docker/relay_backend.Dockerfile
    ports:
      - "12000:80"
    depends_on:
      - redis
      - relay_gateway
    environment:
      - REDIS_HOSTNAME=redis:6379
      - ROUTE_MATRIX_INTERVAL=10s
    healthcheck:
      test: curl --fail http://localhost/ready || exit 1
      interval: 5s
      retries: 10
      timeout: 1s

  server_backend:
    build: 
      context: .
      dockerfile: docker/server_backend.Dockerfile
    ports:
      - "13000:80/tcp"
      - "45000:40000/udp"
    depends_on:
      - magic_backend
      - relay_gateway
    environment:
      - REDIS_HOSTNAME=redis:6379
      - MAGIC_URL=http://magic_backend/magic
      - MAGIC_INTERVAL=10s
      - ROUTE_MATRIX_INTERVAL=10s
      - ROUTE_MATRIX_URL=http://relay_backend/route_matrix
      - SERVER_BACKEND_PUBLIC_KEY=TGHKjEeHPtSgtZfDyuDPcQgtJTyRDtRvGSKvuiWWo0A=
      - SERVER_BACKEND_PRIVATE_KEY=FXwFqzjGlIwUDwiq1N5Um5VUesdr4fP2hVV2cnJ+yARMYcqMR4c+1KC1l8PK4M9xCC0lPJEO1G8ZIq+6JZajQA==
      - RELAY_BACKEND_PRIVATE_KEY=ls5XiwAZRCfyuZAbQ1b9T1bh2VZY8vQ7hp8SdSTSR7M=

  portal_cruncher:
    build: 
      context: .
      dockerfile: docker/portal_cruncher.Dockerfile
    ports:
      - "14000:80"
    depends_on:
      - redis
    environment:
      - REDIS_HOSTNAME=redis:6379

  map_cruncher:
    build: 
      context: .
      dockerfile: docker/map_cruncher.Dockerfile
    ports:
      - "15000:80"
    depends_on:
      - redis
    environment:
      - REDIS_HOSTNAME=redis:6379

  analytics:
    build: 
      context: .
      dockerfile: docker/analytics.Dockerfile
    ports:
      - "16000:80"
    depends_on:
      - redis
      - relay_backend
    environment:
      - REDIS_HOSTNAME=redis:6379
      - COST_MATRIX_URL=http://relay_backend/cost_matrix
      - ROUTE_MATRIX_URL=http://relay_backend/route_matrix

  api:
    build: 
      context: .
      dockerfile: docker/api.Dockerfile
    ports:
      - "50000:80"
    depends_on:
      - redis
      - postgres
    environment:
      - REDIS_HOSTNAME=redis:6379
      - PGSQL_CONFIG=host=postgres port=5432 user=developer password=developer dbname=postgres sslmode=disable
      - API_PRIVATE_KEY=this is the private key that generates API keys. make sure you change this value in production

  relay_1:
    build: 
      context: .
      dockerfile: docker/relay.Dockerfile
    environment:
      - RELAY_NAME=relay_1
      - RELAY_PUBLIC_ADDRESS=10.5.0.5:40000
      - RELAY_PUBLIC_KEY=9SKtwe4Ear59iQyBOggxutzdtVLLc1YQ2qnArgiiz14=
      - RELAY_PRIVATE_KEY=lypnDfozGRHepukundjYAF5fKY1Tw2g7Dxh0rAgMCt8=
      - RELAY_BACKEND_HOSTNAME=http://relay_gateway
      - RELAY_BACKEND_PUBLIC_KEY=SS55dEl9nTSnVVDrqwPeqRv/YcYOZZLXCWTpNBIyX0Y=
    networks:
      relays:
        ipv4_address: 10.5.0.5
    depends_on:
      - relay_backend
    
  relay_2:
    build: 
      context: .
      dockerfile: docker/relay.Dockerfile
    environment:
      - RELAY_NAME=relay_2
      - RELAY_PUBLIC_ADDRESS=10.5.0.6:40000
      - RELAY_PUBLIC_KEY=9SKtwe4Ear59iQyBOggxutzdtVLLc1YQ2qnArgiiz14=
      - RELAY_PRIVATE_KEY=lypnDfozGRHepukundjYAF5fKY1Tw2g7Dxh0rAgMCt8=
      - RELAY_BACKEND_HOSTNAME=http://relay_gateway
      - RELAY_BACKEND_PUBLIC_KEY=SS55dEl9nTSnVVDrqwPeqRv/YcYOZZLXCWTpNBIyX0Y=
    networks:
      relays:
        ipv4_address: 10.5.0.6
    depends_on:
      - relay_backend

  relay_3:
    build: 
      context: .
      dockerfile: docker/relay.Dockerfile
    environment:
      - RELAY_NAME=relay_3
      - RELAY_PUBLIC_ADDRESS=10.5.0.7:40000
      - RELAY_PUBLIC_KEY=9SKtwe4Ear59iQyBOggxutzdtVLLc1YQ2qnArgiiz14=
      - RELAY_PRIVATE_KEY=lypnDfozGRHepukundjYAF5fKY1Tw2g7Dxh0rAgMCt8=
      - RELAY_BACKEND_HOSTNAME=http://relay_gateway
      - RELAY_BACKEND_PUBLIC_KEY=SS55dEl9nTSnVVDrqwPeqRv/YcYOZZLXCWTpNBIyX0Y=
    networks:
      relays:
        ipv4_address: 10.5.0.7
    depends_on:
      - relay_backend

  relay_4:
    build: 
      context: .
      dockerfile: docker/relay.Dockerfile
    environment:
      - RELAY_NAME=relay_4
      - RELAY_PUBLIC_ADDRESS=10.5.0.8:40000
      - RELAY_PUBLIC_KEY=9SKtwe4Ear59iQyBOggxutzdtVLLc1YQ2qnArgiiz14=
      - RELAY_PRIVATE_KEY=lypnDfozGRHepukundjYAF5fKY1Tw2g7Dxh0rAgMCt8=
      - RELAY_BACKEND_HOSTNAME=http://relay_gateway
      - RELAY_BACKEND_PUBLIC_KEY=SS55dEl9nTSnVVDrqwPeqRv/YcYOZZLXCWTpNBIyX0Y=
    networks:
      relays:
        ipv4_address: 10.5.0.8
    depends_on:
      - relay_backend

  relay_5:
    build: 
      context: .
      dockerfile: docker/relay.Dockerfile
    environment:
      - RELAY_NAME=relay_5
      - RELAY_PUBLIC_ADDRESS=10.5.0.9:40000
      - RELAY_PUBLIC_KEY=9SKtwe4Ear59iQyBOggxutzdtVLLc1YQ2qnArgiiz14=
      - RELAY_PRIVATE_KEY=lypnDfozGRHepukundjYAF5fKY1Tw2g7Dxh0rAgMCt8=
      - RELAY_BACKEND_HOSTNAME=http://relay_gateway
      - RELAY_BACKEND_PUBLIC_KEY=SS55dEl9nTSnVVDrqwPeqRv/YcYOZZLXCWTpNBIyX0Y=
    networks:
      relays:
        ipv4_address: 10.5.0.9
    depends_on:
      - relay_backend

  server:
    build: 
      context: .
      dockerfile: docker/server.Dockerfile
    environment:
      - NEXT_LOG_LEVEL=4
      - NEXT_DATACENTER=local
      - NEXT_SERVER_ADDRESS=10.5.0.20
      - NEXT_CUSTOMER_PUBLIC_KEY=leN7D7+9vr24uT4f1Ba8PEEvIQA/UkGZLlT+sdeLRHKsVqaZq723Zw==
      - NEXT_CUSTOMER_PRIVATE_KEY=leN7D7+9vr3TEZexVmvbYzdH1hbpwBvioc6y1c9Dhwr4ZaTkEWyX2Li5Ph/UFrw8QS8hAD9SQZkuVP6x14tEcqxWppmrvbdn
      - NEXT_SERVER_BACKEND_HOSTNAME=server_backend
    networks:
      relays:
        ipv4_address: 10.5.0.20
    depends_on:
      - server_backend

networks:
  relays:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1

volumes:
  postgres:
    driver: local
