version: "3.9"

networks:
  relays:
    driver: bridge
    ipam:
      config:
        - subnet: 10.20.0.0/16
          gateway: 10.20.0.1

volumes:
  postgres:
    driver: local

services:

  base:
    image: network_next_base
    build: 
      context: .
      dockerfile: docker/base.Dockerfile

  postgres:
    build: 
      context: .
      dockerfile: docker/postgres.Dockerfile
    environment:
      POSTGRES_USER: Postgres
      POSTGRES_PASSWORD: Postgres
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - '5436:5432'
    restart: always

  redis:
    image: redis/redis-stack-server:latest
    restart: always

  magic_backend:
    build: 
      context: .
      dockerfile: docker/magic_backend.Dockerfile
    depends_on:
      - base
    ports:
      - "10000:80"

  relay_gateway:
    build: 
      context: .
      dockerfile: docker/relay_gateway.Dockerfile
    ports:
      - "11000:80"
    depends_on:
      - base
      - redis
      - magic_backend
    environment:
      - REDIS_HOSTNAME=redis:6379
      - MAGIC_URL=http://magic_backend/magic
      - MAGIC_INTERVAL=10s
      - RELAY_BACKEND_PUBLIC_KEY=answaVTqPFZaXE5zn3yPv35OduxjnlYHvmpD62VgMlA=
      - RELAY_BACKEND_PRIVATE_KEY=5PHpPbLrTQBSUDDKQKKUAEecM7n2fFwcQLBFlCqoKz4=
      - PING_KEY=O4IBfDec6O/W4vFQeIf+m1OM7PgKXgcCuaPcaqziH0k=
      - RELAY_BACKEND_ADDRESS=10.20.0.200
    networks:
      - default
      - relays
    restart: always

  relay_backend:
    build: 
      context: .
      dockerfile: docker/relay_backend.Dockerfile
    ports:
      - "12000:80"
    depends_on:
      - base
      - redis
      - relay_gateway
    environment:
      - ROUTE_MATRIX_INTERVAL=10s
      - REDIS_HOSTNAME=redis:6379
      - REDIS_PORTAL_HOSTNAME=redis:6379
      - ENABLE_REDIS_TIME_SERIES=true
      - REDIS_TIME_SERIES_HOSTNAME=redis:6379
      - RELAY_BACKEND_PUBLIC_KEY=answaVTqPFZaXE5zn3yPv35OduxjnlYHvmpD62VgMlA=
      - RELAY_BACKEND_PRIVATE_KEY=5PHpPbLrTQBSUDDKQKKUAEecM7n2fFwcQLBFlCqoKz4=
    networks:
      default:
      relays:
        ipv4_address: 10.20.0.200
    restart: always

  session_cruncher:
    build: 
      context: .
      dockerfile: docker/session_cruncher.Dockerfile
    depends_on:
      - base
    ports:
      - "40200:80"
    environment:
      - ENABLE_REDIS_TIME_SERIES=true
      - REDIS_TIME_SERIES_HOSTNAME=redis:6379
    restart: always

  server_cruncher:
    build: 
      context: .
      dockerfile: docker/server_cruncher.Dockerfile
    depends_on:
      - base
    ports:
      - "40300:80"
    restart: always

  server_backend:
    build: 
      context: .
      dockerfile: docker/server_backend.Dockerfile
    ports:
      - "13000:80/tcp"
      - "40000:40000/udp"
    depends_on:
      - base
      - magic_backend
      - relay_gateway
    environment:
      - MAGIC_URL=http://magic_backend/magic
      - MAGIC_INTERVAL=10s
      - ROUTE_MATRIX_INTERVAL=10s
      - ROUTE_MATRIX_URL=http://relay_backend/route_matrix
      - SERVER_BACKEND_PUBLIC_KEY=dicAac5Hx02JPVNraal5ri/9VKtDELQatTQBRQHQan0=
      - SERVER_BACKEND_PRIVATE_KEY=ps+5O/H928YY7SqtOiCUE4Uwf6kJDC4kAHsJMPjTNep2JwBpzkfHTYk9U2tpqXmuL/1Uq0MQtBq1NAFFAdBqfQ==
      - RELAY_BACKEND_PUBLIC_KEY=answaVTqPFZaXE5zn3yPv35OduxjnlYHvmpD62VgMlA=
      - RELAY_BACKEND_PRIVATE_KEY=5PHpPbLrTQBSUDDKQKKUAEecM7n2fFwcQLBFlCqoKz4=
      - PING_KEY=O4IBfDec6O/W4vFQeIf+m1OM7PgKXgcCuaPcaqziH0k=
      - SERVER_BACKEND_ADDRESS=10.20.0.100:40000
      - SESSION_CRUNCHER_URL=http://session_cruncher
      - SERVER_CRUNCHER_URL=http://server_cruncher
      - REDIS_PORTAL_HOSTNAME=redis:6379
      - ENABLE_REDIS_TIME_SERIES=true
      - REDIS_TIME_SERIES_HOSTNAME=redis:6379
    networks:
      default:
      relays:
        ipv4_address: 10.20.0.100
    restart: always

  api:
    build: 
      context: .
      dockerfile: docker/api.Dockerfile
    ports:
      - "50000:80"
    depends_on:
      - base
      - redis
      - postgres
      - server_cruncher
      - session_cruncher
    environment:
      - REDIS_PORTAL_HOSTNAME=redis:6379
      - ENABLE_REDIS_TIME_SERIES=true
      - REDIS_TIME_SERIES_HOSTNAME=redis:6379
      - PGSQL_CONFIG=host=postgres port=5432 user=Postgres password=Postgres dbname=postgres sslmode=disable
      - SESSION_CRUNCHER_URL=http://session_cruncher
      - SERVER_CRUNCHER_URL=http://server_cruncher
      - API_PRIVATE_KEY=fVoJUEVjSAuzdtbdimmOkjwKvGMxxnYkzyETTxhpGqYfQgXrlYsJszkAvVzpuDmU
    restart: always

  relay_0:
    build: 
      context: .
      dockerfile: docker/relay.Dockerfile
    environment:
      - RELAY_NAME=docker.0
      - RELAY_PUBLIC_ADDRESS=10.20.1.0:40000
      - RELAY_BACKEND_URL=http://relay_gateway
      - RELAY_PUBLIC_KEY=DkmtxHmjox9lLbEHExYjvJHdA0Q6VUV0MaHOtwudPWk=
      - RELAY_PRIVATE_KEY=QMgmGF+Cii7RxGB99wTLmrMvYGNgcKphHJvyqyTCHzE=
      - RELAY_BACKEND_PUBLIC_KEY=answaVTqPFZaXE5zn3yPv35OduxjnlYHvmpD62VgMlA=
    networks:
      relays:
        ipv4_address: 10.20.1.0
    depends_on:
      - base
      - relay_backend
    restart: always

  relay_1:
    build: 
      context: .
      dockerfile: docker/relay.Dockerfile
    environment:
      - RELAY_NAME=docker.1
      - RELAY_PUBLIC_ADDRESS=10.20.1.1:40000
      - RELAY_BACKEND_URL=http://relay_gateway
      - RELAY_PUBLIC_KEY=DkmtxHmjox9lLbEHExYjvJHdA0Q6VUV0MaHOtwudPWk=
      - RELAY_PRIVATE_KEY=QMgmGF+Cii7RxGB99wTLmrMvYGNgcKphHJvyqyTCHzE=
      - RELAY_BACKEND_PUBLIC_KEY=answaVTqPFZaXE5zn3yPv35OduxjnlYHvmpD62VgMlA=
    networks:
      relays:
        ipv4_address: 10.20.1.1
    depends_on:
      - base
      - relay_backend
    restart: always

  relay_2:
    build: 
      context: .
      dockerfile: docker/relay.Dockerfile
    environment:
      - RELAY_NAME=docker.2
      - RELAY_PUBLIC_ADDRESS=10.20.1.2:40000
      - RELAY_BACKEND_URL=http://relay_gateway
      - RELAY_PUBLIC_KEY=DkmtxHmjox9lLbEHExYjvJHdA0Q6VUV0MaHOtwudPWk=
      - RELAY_PRIVATE_KEY=QMgmGF+Cii7RxGB99wTLmrMvYGNgcKphHJvyqyTCHzE=
      - RELAY_BACKEND_PUBLIC_KEY=answaVTqPFZaXE5zn3yPv35OduxjnlYHvmpD62VgMlA=
    networks:
      relays:
        ipv4_address: 10.20.1.2
    depends_on:
      - base
      - relay_backend
    restart: always

  portal:
    build:
      context: .
      dockerfile: docker/portal.Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - api
    restart: always

  raspberry_backend:
    build: 
      context: .
      dockerfile: docker/raspberry_backend.Dockerfile
    depends_on:
      - base
    ports:
      - "40100:80"
    environment:
      - REDIS_HOSTNAME=redis:6379
    networks:
      default:
      relays:
        ipv4_address: 10.20.0.60

  raspberry_server_0:
    build: 
      context: .
      dockerfile: docker/raspberry_server.Dockerfile
    environment:
      - NEXT_DATACENTER=docker
      - NEXT_SERVER_ADDRESS=10.20.2.0
      - NEXT_BIND_ADDRESS=0.0.0.0:40000
      - NEXT_SERVER_BACKEND_HOSTNAME=server_backend
      - NEXT_BUYER_PUBLIC_KEY=5Vr+VZdUXckgQwHdPRftc/8IUWDL7ZftvBOzE/+Zpp+PIjSU0Kxmwg==
      - NEXT_BUYER_PRIVATE_KEY=5Vr+VZdUXckPZsd89NGTmXASmmlHRuWiyVs7orAxRV6hDkvTc3VMtCBDAd09F+1z/whRYMvtl+28E7MT/5mmn48iNJTQrGbC
      - NEXT_SERVER_BACKEND_PUBLIC_KEY=dicAac5Hx02JPVNraal5ri/9VKtDELQatTQBRQHQan0=
      - NEXT_RELAY_BACKEND_PUBLIC_KEY=answaVTqPFZaXE5zn3yPv35OduxjnlYHvmpD62VgMlA=
      - RASPBERRY_BACKEND_URL=http://raspberry_backend
    networks:
      relays:
        ipv4_address: 10.20.2.0
    depends_on:
      - base
      - server_backend
    restart: always

  raspberry_server_1:
    build: 
      context: .
      dockerfile: docker/raspberry_server.Dockerfile
    environment:
      - NEXT_DATACENTER=docker
      - NEXT_SERVER_ADDRESS=10.20.2.1
      - NEXT_BIND_ADDRESS=0.0.0.0:40000
      - NEXT_SERVER_BACKEND_HOSTNAME=server_backend
      - NEXT_BUYER_PUBLIC_KEY=5Vr+VZdUXckgQwHdPRftc/8IUWDL7ZftvBOzE/+Zpp+PIjSU0Kxmwg==
      - NEXT_BUYER_PRIVATE_KEY=5Vr+VZdUXckPZsd89NGTmXASmmlHRuWiyVs7orAxRV6hDkvTc3VMtCBDAd09F+1z/whRYMvtl+28E7MT/5mmn48iNJTQrGbC
      - NEXT_SERVER_BACKEND_PUBLIC_KEY=dicAac5Hx02JPVNraal5ri/9VKtDELQatTQBRQHQan0=
      - NEXT_RELAY_BACKEND_PUBLIC_KEY=answaVTqPFZaXE5zn3yPv35OduxjnlYHvmpD62VgMlA=
      - RASPBERRY_BACKEND_URL=http://raspberry_backend
    networks:
      relays:
        ipv4_address: 10.20.2.1
    depends_on:
      - base
      - server_backend
    restart: always

  raspberry_server_2:
    build: 
      context: .
      dockerfile: docker/raspberry_server.Dockerfile
    environment:
      - NEXT_DATACENTER=docker
      - NEXT_SERVER_ADDRESS=10.20.2.2
      - NEXT_BIND_ADDRESS=0.0.0.0:40000
      - NEXT_SERVER_BACKEND_HOSTNAME=server_backend
      - NEXT_BUYER_PUBLIC_KEY=5Vr+VZdUXckgQwHdPRftc/8IUWDL7ZftvBOzE/+Zpp+PIjSU0Kxmwg==
      - NEXT_BUYER_PRIVATE_KEY=5Vr+VZdUXckPZsd89NGTmXASmmlHRuWiyVs7orAxRV6hDkvTc3VMtCBDAd09F+1z/whRYMvtl+28E7MT/5mmn48iNJTQrGbC
      - NEXT_SERVER_BACKEND_PUBLIC_KEY=dicAac5Hx02JPVNraal5ri/9VKtDELQatTQBRQHQan0=
      - NEXT_RELAY_BACKEND_PUBLIC_KEY=answaVTqPFZaXE5zn3yPv35OduxjnlYHvmpD62VgMlA=
      - RASPBERRY_BACKEND_URL=http://raspberry_backend
    networks:
      relays:
        ipv4_address: 10.20.2.2
    depends_on:
      - base
      - server_backend
    restart: always

  raspberry_server_3:
    build: 
      context: .
      dockerfile: docker/raspberry_server.Dockerfile
    environment:
      - NEXT_DATACENTER=docker
      - NEXT_SERVER_ADDRESS=10.20.2.3
      - NEXT_BIND_ADDRESS=0.0.0.0:40000
      - NEXT_SERVER_BACKEND_HOSTNAME=server_backend
      - NEXT_BUYER_PUBLIC_KEY=5Vr+VZdUXckgQwHdPRftc/8IUWDL7ZftvBOzE/+Zpp+PIjSU0Kxmwg==
      - NEXT_BUYER_PRIVATE_KEY=5Vr+VZdUXckPZsd89NGTmXASmmlHRuWiyVs7orAxRV6hDkvTc3VMtCBDAd09F+1z/whRYMvtl+28E7MT/5mmn48iNJTQrGbC
      - NEXT_SERVER_BACKEND_PUBLIC_KEY=dicAac5Hx02JPVNraal5ri/9VKtDELQatTQBRQHQan0=
      - NEXT_RELAY_BACKEND_PUBLIC_KEY=answaVTqPFZaXE5zn3yPv35OduxjnlYHvmpD62VgMlA=
      - RASPBERRY_BACKEND_URL=http://raspberry_backend
    networks:
      relays:
        ipv4_address: 10.20.2.3
    depends_on:
      - base
      - server_backend
    restart: always

  raspberry_server_4:
    build: 
      context: .
      dockerfile: docker/raspberry_server.Dockerfile
    environment:
      - NEXT_DATACENTER=docker
      - NEXT_SERVER_ADDRESS=10.20.2.4
      - NEXT_BIND_ADDRESS=0.0.0.0:40000
      - NEXT_SERVER_BACKEND_HOSTNAME=server_backend
      - NEXT_BUYER_PUBLIC_KEY=5Vr+VZdUXckgQwHdPRftc/8IUWDL7ZftvBOzE/+Zpp+PIjSU0Kxmwg==
      - NEXT_BUYER_PRIVATE_KEY=5Vr+VZdUXckPZsd89NGTmXASmmlHRuWiyVs7orAxRV6hDkvTc3VMtCBDAd09F+1z/whRYMvtl+28E7MT/5mmn48iNJTQrGbC
      - NEXT_SERVER_BACKEND_PUBLIC_KEY=dicAac5Hx02JPVNraal5ri/9VKtDELQatTQBRQHQan0=
      - NEXT_RELAY_BACKEND_PUBLIC_KEY=answaVTqPFZaXE5zn3yPv35OduxjnlYHvmpD62VgMlA=
      - RASPBERRY_BACKEND_URL=http://raspberry_backend
    networks:
      relays:
        ipv4_address: 10.20.2.4
    depends_on:
      - base
      - server_backend
    restart: always

  raspberry_clients_0:
    build: 
      context: .
      dockerfile: docker/raspberry_client.Dockerfile
    environment:
      - RASPBERRY_BACKEND_URL=http://raspberry_backend
      - RASPBERRY_NUM_CLIENTS=128
      - NEXT_BUYER_PUBLIC_KEY=5Vr+VZdUXckgQwHdPRftc/8IUWDL7ZftvBOzE/+Zpp+PIjSU0Kxmwg==
      - NEXT_BUYER_PRIVATE_KEY=5Vr+VZdUXckPZsd89NGTmXASmmlHRuWiyVs7orAxRV6hDkvTc3VMtCBDAd09F+1z/whRYMvtl+28E7MT/5mmn48iNJTQrGbC
      - NEXT_SERVER_BACKEND_PUBLIC_KEY=dicAac5Hx02JPVNraal5ri/9VKtDELQatTQBRQHQan0=
      - NEXT_RELAY_BACKEND_PUBLIC_KEY=answaVTqPFZaXE5zn3yPv35OduxjnlYHvmpD62VgMlA=
    networks:
      relays:
        ipv4_address: 10.20.3.0
    depends_on:
      - base
      - server_backend
    restart: always

  raspberry_clients_1:
    build: 
      context: .
      dockerfile: docker/raspberry_client.Dockerfile
    environment:
      - RASPBERRY_BACKEND_URL=http://raspberry_backend
      - RASPBERRY_NUM_CLIENTS=128
      - NEXT_BUYER_PUBLIC_KEY=5Vr+VZdUXckgQwHdPRftc/8IUWDL7ZftvBOzE/+Zpp+PIjSU0Kxmwg==
      - NEXT_BUYER_PRIVATE_KEY=5Vr+VZdUXckPZsd89NGTmXASmmlHRuWiyVs7orAxRV6hDkvTc3VMtCBDAd09F+1z/whRYMvtl+28E7MT/5mmn48iNJTQrGbC
      - NEXT_SERVER_BACKEND_PUBLIC_KEY=dicAac5Hx02JPVNraal5ri/9VKtDELQatTQBRQHQan0=
      - NEXT_RELAY_BACKEND_PUBLIC_KEY=answaVTqPFZaXE5zn3yPv35OduxjnlYHvmpD62VgMlA=
    networks:
      relays:
        ipv4_address: 10.20.3.1
    depends_on:
      - base
      - server_backend
    restart: always

  raspberry_clients_2:
    build: 
      context: .
      dockerfile: docker/raspberry_client.Dockerfile
    environment:
      - RASPBERRY_BACKEND_URL=http://raspberry_backend
      - RASPBERRY_NUM_CLIENTS=128
      - NEXT_BUYER_PUBLIC_KEY=5Vr+VZdUXckgQwHdPRftc/8IUWDL7ZftvBOzE/+Zpp+PIjSU0Kxmwg==
      - NEXT_BUYER_PRIVATE_KEY=5Vr+VZdUXckPZsd89NGTmXASmmlHRuWiyVs7orAxRV6hDkvTc3VMtCBDAd09F+1z/whRYMvtl+28E7MT/5mmn48iNJTQrGbC
      - NEXT_SERVER_BACKEND_PUBLIC_KEY=dicAac5Hx02JPVNraal5ri/9VKtDELQatTQBRQHQan0=
      - NEXT_RELAY_BACKEND_PUBLIC_KEY=answaVTqPFZaXE5zn3yPv35OduxjnlYHvmpD62VgMlA=
    networks:
      relays:
        ipv4_address: 10.20.3.2
    depends_on:
      - base
      - server_backend
    restart: always

  raspberry_clients_3:
    build: 
      context: .
      dockerfile: docker/raspberry_client.Dockerfile
    environment:
      - RASPBERRY_BACKEND_URL=http://raspberry_backend
      - RASPBERRY_NUM_CLIENTS=128
      - NEXT_BUYER_PUBLIC_KEY=5Vr+VZdUXckgQwHdPRftc/8IUWDL7ZftvBOzE/+Zpp+PIjSU0Kxmwg==
      - NEXT_BUYER_PRIVATE_KEY=5Vr+VZdUXckPZsd89NGTmXASmmlHRuWiyVs7orAxRV6hDkvTc3VMtCBDAd09F+1z/whRYMvtl+28E7MT/5mmn48iNJTQrGbC
      - NEXT_SERVER_BACKEND_PUBLIC_KEY=dicAac5Hx02JPVNraal5ri/9VKtDELQatTQBRQHQan0=
      - NEXT_RELAY_BACKEND_PUBLIC_KEY=answaVTqPFZaXE5zn3yPv35OduxjnlYHvmpD62VgMlA=
    networks:
      relays:
        ipv4_address: 10.20.3.3
    depends_on:
      - base
      - server_backend
    restart: always

  raspberry_clients_4:
    build: 
      context: .
      dockerfile: docker/raspberry_client.Dockerfile
    environment:
      - RASPBERRY_BACKEND_URL=http://raspberry_backend
      - RASPBERRY_NUM_CLIENTS=128
      - NEXT_BUYER_PUBLIC_KEY=5Vr+VZdUXckgQwHdPRftc/8IUWDL7ZftvBOzE/+Zpp+PIjSU0Kxmwg==
      - NEXT_BUYER_PRIVATE_KEY=5Vr+VZdUXckPZsd89NGTmXASmmlHRuWiyVs7orAxRV6hDkvTc3VMtCBDAd09F+1z/whRYMvtl+28E7MT/5mmn48iNJTQrGbC
      - NEXT_SERVER_BACKEND_PUBLIC_KEY=dicAac5Hx02JPVNraal5ri/9VKtDELQatTQBRQHQan0=
      - NEXT_RELAY_BACKEND_PUBLIC_KEY=answaVTqPFZaXE5zn3yPv35OduxjnlYHvmpD62VgMlA=
    networks:
      relays:
        ipv4_address: 10.20.3.4
    depends_on:
      - base
      - server_backend
    restart: always

  raspberry_clients_5:
    build: 
      context: .
      dockerfile: docker/raspberry_client.Dockerfile
    environment:
      - RASPBERRY_BACKEND_URL=http://raspberry_backend
      - RASPBERRY_NUM_CLIENTS=128
      - NEXT_BUYER_PUBLIC_KEY=5Vr+VZdUXckgQwHdPRftc/8IUWDL7ZftvBOzE/+Zpp+PIjSU0Kxmwg==
      - NEXT_BUYER_PRIVATE_KEY=5Vr+VZdUXckPZsd89NGTmXASmmlHRuWiyVs7orAxRV6hDkvTc3VMtCBDAd09F+1z/whRYMvtl+28E7MT/5mmn48iNJTQrGbC
      - NEXT_SERVER_BACKEND_PUBLIC_KEY=dicAac5Hx02JPVNraal5ri/9VKtDELQatTQBRQHQan0=
      - NEXT_RELAY_BACKEND_PUBLIC_KEY=answaVTqPFZaXE5zn3yPv35OduxjnlYHvmpD62VgMlA=
    networks:
      relays:
        ipv4_address: 10.20.3.5
    depends_on:
      - base
      - server_backend
    restart: always

  raspberry_clients_6:
    build: 
      context: .
      dockerfile: docker/raspberry_client.Dockerfile
    environment:
      - RASPBERRY_BACKEND_URL=http://raspberry_backend
      - RASPBERRY_NUM_CLIENTS=128
      - NEXT_BUYER_PUBLIC_KEY=5Vr+VZdUXckgQwHdPRftc/8IUWDL7ZftvBOzE/+Zpp+PIjSU0Kxmwg==
       NEXT_BUYER_PRIVATE_KEY=AN+VWuqgAQdhmzB4XOT89baswrIaX6WS7dTIW8U6deMZdoemQh9qoN3l35B5Ppqk1/4Ztv2uoUEy2Tkz4agy/BLUSrPvrhf8
      - NEXT_SERVER_BACKEND_PUBLIC_KEY=dicAac5Hx02JPVNraal5ri/9VKtDELQatTQBRQHQan0=
      - NEXT_RELAY_BACKEND_PUBLIC_KEY=answaVTqPFZaXE5zn3yPv35OduxjnlYHvmpD62VgMlA=
    networks:
      relays:
        ipv4_address: 10.20.3.6
    depends_on:
      - base
      - server_backend
    restart: always

  raspberry_clients_7:
    build: 
      context: .
      dockerfile: docker/raspberry_client.Dockerfile
    environment:
      - RASPBERRY_BACKEND_URL=http://raspberry_backend
      - RASPBERRY_NUM_CLIENTS=128
      - NEXT_BUYER_PUBLIC_KEY=5Vr+VZdUXckgQwHdPRftc/8IUWDL7ZftvBOzE/+Zpp+PIjSU0Kxmwg==
      - NEXT_BUYER_PRIVATE_KEY=5Vr+VZdUXckPZsd89NGTmXASmmlHRuWiyVs7orAxRV6hDkvTc3VMtCBDAd09F+1z/whRYMvtl+28E7MT/5mmn48iNJTQrGbC
      - NEXT_SERVER_BACKEND_PUBLIC_KEY=dicAac5Hx02JPVNraal5ri/9VKtDELQatTQBRQHQan0=
      - NEXT_RELAY_BACKEND_PUBLIC_KEY=answaVTqPFZaXE5zn3yPv35OduxjnlYHvmpD62VgMlA=
    networks:
      relays:
        ipv4_address: 10.20.3.7
    depends_on:
      - base
      - server_backend
    restart: always
