version: v1.0
name: Production Deploy
agent:
  machine:
    type: e1-standard-8
    os_image: ubuntu1804
global_job_config:
  prologue:
    commands:
      - sudo apt-get update && sudo apt-get -y install libsodium-dev
      - gcloud auth activate-service-account --key-file=/home/semaphore/gcp-service-account.json
      - gcloud auth configure-docker -q
      - checkout
      - sem-version go 1.13
      - make clean
blocks:
  - name: Build
    dependencies: []
    task:
      jobs:
        - name: Build Artifacts
          parallelism: 4
          commands:
            - make build-billing-prod-artifact
            - make build-portal-prod-artifact
            - make build-relay-backend-prod-artifact
            - make build-server-backend-prod-artifact
            - artifact push workflow ./dist/billing.prod.tar.gz
            - artifact push workflow ./dist/portal.prod.tar.gz
            - artifact push workflow ./dist/relay_backend.prod.tar.gz
            - artifact push workflow ./dist/server_backend.prod.tar.gz
      secrets:
        - name: google-cloud-platform-prod
  - name: Publish
    dependencies: ["Build"]
    task:
      jobs:
        - name: Publish Artifacts
          parallelism: 5
          commands:
            - artifact pull workflow ./dist/billing.prod.tar.gz
            - artifact pull workflow ./dist/portal.prod.tar.gz
            - artifact pull workflow ./dist/relay_backend.prod.tar.gz
            - artifact pull workflow ./dist/server_backend.prod.tar.gz
            - make publish-billing-prod-artifact
            - make publish-portal-prod-artifact
            - make publish-relay-backend-prod-artifact
            - make publish-server-backend-prod-artifact
            - make publish-bootstrap-script-prod
      secrets:
        - name: google-cloud-platform-prod