name: Tests

# This workflow will run on master branch and on any pull requests targeting master
on:
  push:
    branches:
      - master
    tags: []
  pull_request:
  
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Check out code
        uses: actions/checkout@v1

      - name: Run tests
        run: make test